### PR TITLE
Laravel 8 support

### PR DESCRIPTION
**Pull request by driesvints**
Needed for us to roll out Laravel 8 support for Nexmo Notification Channel: https://github.com/laravel/nexmo-notification-channel/pull/38

### CODE REVIEW

**Comment by dragonmantank** [comment]
We are going to have a BC breaking change here soon, we've changed a namespace and return type with SMS. What's the timeframe on Laravel 8? Might as well roll those two things together if possible.

**Comment by driesvints** [comment]
We're launching it on September 8. We can definitely also do a major release on our end if necessary.

**Comment by dragonmantank** [comment]
Awesome. Expect a PR from me within a few days then!

**Comment by driesvints** [comment]
Thanks Chris : )

**Comment by driesvints** [comment]
@dragonmantank hey Chris. Laravel 8 release is next week. Have you had time to look into that PR already? Shall we just do a 2.3.0 with Laravel 8 support? Then it's less pressure for you to work on a PR and we can do a next major release for laravel nexmo notificiation channel afterwards.

**Comment by dragonmantank** [comment]
Started working on the PR, but I'll have some other changes that will impact the mainline Nexmo Notifications package (including a brand rename to Vonage), so I'll work with you all on that once Laravel 8 comes out.

I'll cut 2.3.0 here in a moment, and do a larger PR for the next major Laravel/Laravel Notifications release

**Comment by driesvints** [comment]
@dragonmantank perfect! Thank you.

**Pull request merged**
