### PR TITLE
Refacto and enhancement

### PR DESCRIPTION
**Pull request by percymamedy**
Added .gitignore and .gitattributes files. 

Also made some code changes to the Service provider to reflect the coding style of Laravel.

### CODE REVIEW

**Comment by percymamedy** [comment]
Seems this PR will not get reviewed and even didn't deserve a response. Closing for now.

**Comment by leggetter** [comment]
@percymamedy sorry this appears to have been missed. @mheap just recently joined us and I'm sure would be willing to provide some feedback.

**Comment by mheap** [comment]
Morning @percymamedy,

*So* sorry that I didn't spot this earlier. As Phil mentioned I recently joined the team and somehow missed this PR.

I've had a look through and it looks great to me! I'd like to test the PR on my local machine this afternoon but assuming everything works as expected I'll release a new version this evening

**Comment by percymamedy** [comment]
Thank you for reviewing my PR.. Keep me posted if any updates need be.. I can write some unit tests as well if necessary..

**Comment by mheap** [comment]
If you could provide tests too, that would be amazing 👍

**Comment by percymamedy** [comment]
@mheap done with the tests and refactoring here is what I basically added:

- Refactored NexmoServiceProvider.
- Pimp up README with Badges.
- Added some test cases.

**Pull request merged**
