### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by driesvints**
Laravel 7 is almost going to be released so I'm sending this in also because we need this to get our own test suite to pass: https://github.com/laravel/nexmo-notification-channel/pull/33

### CODE REVIEW

**Comment by dragonmantank** [comment]
Thanks! I'll cut a point release by Monday after I am back from PHP UK.

**Comment by driesvints** [comment]
Thanks Chris!

**Comment by driesvints** [comment]
Hey @dragonmantank, if you have a moment can you please tag a new release? Then laravel/nexmo-notification-channel is all ready for next Tuesday's Laravel 7 release :)

**Comment by dragonmantank** [comment]
This just went out, so hopefully Packagist will have it available soon!

**Comment by driesvints** [comment]
Awesome, thanks a bunch! :)

**Pull request merged**
